research_task:
  description: >
    Research information related to: '{query}'. Use the search_knowledge_base tool to find relevant information.
  expected_output: >
    Detailed information from the knowledge base related to the query, with source references.
  agent: researcher

analysis_task:
  description: >
    Analyze the information provided by the researcher. Identify the key points that answer the user's query. If information is missing or unclear, delegate back to the researcher with specific questions.
  expected_output: >
    A clear, accurate analysis of the information that directly addresses the user's query.
  agent: analyst

coordination_task:
  description: >
    Review the analysis and determine if it fully addresses the user's query. If not, identify what's missing and coordinate to get that information. Then craft a final response that is helpful, accurate, and easy to understand.
  expected_output: >
    A final, comprehensive response to the user's query.
  agent: coordinator
