research_task:
  description: >
    Research information related to: '{query}'. FIRST, determine if the query is relevant to Aparavi's knowledge base and within scope of our system's purpose. If the query is clearly off-topic, unrelated to Aparavi's domain, or appears to be using the system as a general-purpose LLM, state this explicitly and do not proceed with further research. For relevant queries, use the search_knowledge_base tool systematically to find appropriate information.
  expected_output: >
    Either: 1) A clear statement that the query is outside Aparavi's domain with a brief explanation of our system's intended purpose, OR 2) Detailed information from the knowledge base with explicit source references. Include your search methodology and note any areas where information might be incomplete.
  agent: researcher

analysis_task:
  description: >
    Analyze the information provided by the researcher. If the researcher determined the query is out-of-scope, confirm this assessment and prepare a respectful boundary statement. For in-scope queries, identify key points that directly address the user's question. If information is missing or unclear for relevant queries, delegate back to the researcher with specific questions.
  expected_output: >
    Either: 1) A confirmation that the query is outside our system's scope with a suggested response that maintains boundaries while being respectful, OR 2) A clear, accurate analysis of the information that directly addresses the user's in-scope query, including source references.
  agent: analyst

coordination_task:
  description: >
    Review the analysis. For out-of-scope queries, deliver a clear, friendly response that explains our system's purpose and limitations. Do not attempt to answer questions unrelated to Aparavi's knowledge domain, even if you technically could. For in-scope queries, ensure the response fully addresses the user's question with accurate information from our knowledge base. If critical information is missing for an in-scope query, coordinate to obtain it.
  expected_output: >
    For out-of-scope queries: A polite explanation that this system is designed specifically for Aparavi-related information and cannot be used as a general-purpose assistant. Suggest the user reformulate their question to be relevant to Aparavi's domain.
    For in-scope queries: A comprehensive, accurate response based on Aparavi's knowledge base that directly addresses the user's question.
  agent: coordinator